config/routes.rb
Rails.application.routes.draw do

  resources :createorganism
  resources :createorigin
  resources :createdrug
  resources :createmutation
  resources :dashboards

  resources :mutpubs

  devise_for :users
  resources :haves

  resources :publications

  resources :stats

  resources :mutations

  resources :genes

  resources :drugs

  resources :resists

  resources :isolateds

  resources :origins

  resources :organisms

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/faq'

end

app/models/isolated.rb
class Isolated < ActiveRecord::Base
  belongs_to :origin
  belongs_to :organism
  has_many :genes,	:dependent => :destroy
  has_many :resists, :dependent => :destroy
  has_many :drugs, :through => :resists
  accepts_nested_attributes_for :genes, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :resists, :reject_if => lambda { |a| a[:mic].blank? } , :allow_destroy => true

  validates :name, :disease,  presence: true
  validates :n_samples, numericality: { only_integer: true}
  validates :name, length: { maximum: 30}, uniqueness: true
  validates :disease, length: { maximum: 100}


  def self.search (search) 
      where("name like ? OR disease like ?", "%#{search}%", "%#{search}%")
  end

 
end

app/controllers/isolateds_controller.rb
class IsolatedsController < ApplicationController
  before_action :set_isolated, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:show, :edit, :new, :destroy, :update, :create]
  before_action :set_orgorig, only: [:new, :edit, :update, :create]
  # GET /isolateds
  # GET /isolateds.json
  def index
    if params[:search]
      @isolateds = Isolated.search(params[:search]).order(:name, :disease).paginate(:per_page => 3, :page => params[:page])
    else
      @isolateds = Isolated.all.order(:name, :disease).paginate(:per_page => 3, :page => params[:page])
    end
  end

  # GET /isolateds/1
  # GET /isolateds/1.json
  def show
  end

  # GET /isolateds/new
  def new
    @isolated = Isolated.new
    @n = params[:newi] #isolated.id
  end

  # GET /isolateds/1/edit
  def edit
  end

  # POST /isolateds
  # POST /isolateds.json
  def create
    @isolated = Isolated.new(isolated_params)

    respond_to do |format|
      if @isolated.save
        format.html { redirect_to @isolated, notice: 'Isolated was successfully created.' }
        format.json { render :show, status: :created, location: @isolated }
      else
        format.html { render :new }
        format.json { render json: @isolated.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /isolateds/1
  # PATCH/PUT /isolateds/1.json
  def update
    respond_to do |format|
      if @isolated.update(isolated_params)
        format.html { redirect_to @isolated, notice: 'Isolated was successfully updated.' }
        format.json { render :show, status: :ok, location: @isolated }
      else
        format.html { render :edit }
        format.json { render json: @isolated.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /isolateds/1
  # DELETE /isolateds/1.json
  def destroy
    @isolated.destroy
    respond_to do |format|
      format.html { redirect_to isolateds_url, notice: 'Isolated was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_isolated
      @isolated = Isolated.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def isolated_params
      params.require(:isolated).permit(:name, :disease, :n_samples, :origin_id, :organism_id)
    end

    def set_orgorig
        @origins = Origin.all
        @organisms = Organism.all
    end
end

app/helpers/isolateds_helper.rb
module IsolatedsHelper
end

app/views/isolateds/_form.html.erb
<div class="panel panel-info">
<div class="panel-heading"><strong>Isolated</strong></div>
<div class="panel-body">
<%= form_for @isolated, :html => { :class => "form-horizontal isolated" } do |f| %>

    <% if @isolated.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@isolated.errors.count, "error") %> prohibited this isolated from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @isolated.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@isolated[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :Disease, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :disease, :class => 'form-control' %>
    </div>
    <%= error_span(@isolated[:disease]) %>
  </div>
  <div class="control-group">
    <%= f.label :Number_of_Samples, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :n_samples, :class => 'form-control' %>
    </div>
    <%= error_span(@isolated[:n_samples]) %>
  </div>
  <div class="control-group">
    <%= f.label :Origin, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :origin_id, @origins, :id, :all, prompt: true, :class => 'form-control' %>
    </div>
    <%= error_span(@isolated[:origin_id]) %>
  </div>
  <div class="control-group">
    <% if @n == nil%>
         <%= f.label :Organism, :class => 'control-label' %>
         <%= f.collection_select :organism_id, @organisms, :id, :name, prompt: true, :class => 'form-control' %>
    <%else%>
         <%= f.label :Organism, :class => 'control-label' %>
         <%= f.collection_select :organism_id, @organisms, :id, :name, :selected => "#{@n}" %>
    <%end%>
  </div>
  <hr>
  <%= f.submit "Submit", :class => 'btn active btn-sm btn-primary'%>
  <%= link_to " Cancel",
            isolateds_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-remove' %>
<% end %>
</div>
</div>

app/views/isolateds/edit.html.erb
<%- model_class = Isolated -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/isolateds/index.html.erb
<%- model_class = Isolated -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag isolateds_path, :method => 'get' do %>
  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-search"></span>
    <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Search the Isolated here'%>
    <span class="input-group-addon" id="sizing-addon1"><%= submit_tag "Search", :name=> nil %></span>
  </div>
<%end%>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="info"><%= model_class.human_attribute_name(:Id) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Name) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Disease) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Number_of_Samples) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Type_origin) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Laboratory) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Organism) %></th>
      <th class="info"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @isolateds.any? == true%>
    <% @isolateds.each do |isolated| %>
      <tr>
        <td><%= link_to isolated.id, isolated_path(isolated) %></td>
        <td><%= isolated.name %></td>
        <td><%= isolated.disease %></td>
        <td><%= isolated.n_samples %></td>
        <td><%= isolated.origin.origin_t %></td>
        <td><%= isolated.origin.lab_name %></td>
        <td><%= isolated.organism.name %></td>
        <td>
          <%= link_to " show", isolated_path(isolated), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
          <%= link_to " edit", edit_isolated_path(isolated), :class => 'btn active btn-default btn-xs glyphicon glyphicon-edit' %>
          <%= link_to " Delete", isolated_path(isolated),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure you want delete the Isolated your genes associated?'},
                      :class => 'btn active btn-xs btn-danger glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
    <%else%>
      <tr>
          <td colspan="8"><%= "Don't exist isolateds" %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<div class="pager btn-sm" align="center">
  <%= will_paginate @isolateds %>
  </div>
  <hr>
<%= link_to " New Isolated",
            new_isolated_path,
            :class => 'btn active btn-sm btn-primary glyphicon glyphicon-plus-sign' %>

app/views/isolateds/new.html.erb
<%- model_class = Isolated -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/isolateds/show.html.erb
<%- model_class = Isolated -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Name) %>:</strong></dt>
  <dd><%= @isolated.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Disease) %>:</strong></dt>
  <dd><%= @isolated.disease %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Number_of_Samples) %>:</strong></dt>
  <dd><%= @isolated.n_samples %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Origin) %>:</strong></dt>
  <dd><%= @isolated.origin.origin_t %></dd>
  <dd><%= @isolated.origin.lab_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Organism) %>:</strong></dt>
  <dd><%= @isolated.organism.name %></dd>
  <dd><%= link_to "Go to Organism", organism_path(@isolated.organism.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %></dd>
    <hr>
    <div class="panel panel-info">
      <div class="panel-heading" style="font-size: 18px" align="center"><b> Drugs Resistance: </b></div>
      
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:MIC) %></th>
                <th><%= model_class.human_attribute_name(:Name) %></th>
                <th><%= model_class.human_attribute_name(:Reference) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% if @isolated.drugs.any? == true%>
              <% @isolated.resists.each do |drug| %>
                <tr>
                  <td><%= drug.mic %></td>
                  <td><%= drug.drug.name %></td>
                  <td><%= drug.drug.reference %></td>
                  <td>
                    <%= link_to "Go to Drug", drug_path(drug.drug.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %>
                     <%= link_to " Show association", resist_path(drug.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
                  </td>
                </tr>
              <% end %>
              <%else%>
                <tr>
                    <td colspan="4"><%= "This isolated don't have resistance a drugs" %></td>
                </tr>
              <%end%>
            </tbody>
            </table>
    </div>
    <%= form_tag new_resist_path, :method => 'get' do %>
          <div class="input-group">
            <strong><%=" Do you need a new resist drug for this isolated, with ID   "%>
            <%= text_field_tag :newd, @isolated.id, :readonly => true, :class => 'textbox' %></strong>
            <%= submit_tag "New Drug", :name=> nil, :class => 'btn active btn-sm btn-primary' %>
          </div>
    <%end%>
    <hr>
    <div class="panel panel-info">
      <div class="panel-heading" style="font-size: 18px" align="center"><b> Associated Genes: </b></div>
      
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:Name) %></th>
                <th><%= model_class.human_attribute_name(:Reference) %></th>
                <th><%= model_class.human_attribute_name(:Sequence) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% if @isolated.genes.any? == true%>
              <% @isolated.genes.each do |gene| %>
                <tr>
                  <td><%= gene.name %></td>
                  <td><%= gene.reference %></td>
                  <td><%= gene.sequence %></td>
                  <td>
                    <%= link_to "Go to Gene", gene_path(gene.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %>
                  </td>
                </tr>
              <% end %>
              <%else%>
                <tr>
                    <td colspan="4"><%= "This isolated don't have genes associated"%></td>
                </tr>
              <%end%>
            </tbody>
            </table>
    </div>
    <%= form_tag new_gene_path, :method => 'get' do %>
          <div class="input-group">
            <strong><%=" Do you need a new gene for this isolated, with ID   "%>
            <%= text_field_tag :newg, @isolated.id, :readonly => true, :class => 'textbox' %></strong>
            <%= submit_tag "New Gene", :name=> nil, :class => 'btn active btn-sm btn-primary' %>
          </div>
    <%end%>
</dl>
<hr>
<%= link_to " Back", isolateds_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-share-alt'  %>
<%= link_to " Edit", edit_isolated_path(@isolated), :class => 'btn active btn-sm btn-default glyphicon glyphicon-edit' %>
<%= link_to " Delete", isolated_path(@isolated),
              :method => 'delete',
              :data => { :confirm => 'Are you sure you want delete the Isolated your genes associated?' },
              :class => 'btn active btn-sm btn-danger glyphicon glyphicon-remove' %>