config/routes.rb
Rails.application.routes.draw do

  resources :createorganism
  resources :createorigin
  resources :createdrug
  resources :createmutation
  resources :dashboards

  resources :mutpubs

  devise_for :users
  resources :haves

  resources :publications

  resources :stats

  resources :mutations

  resources :genes

  resources :drugs

  resources :resists

  resources :isolateds

  resources :origins

  resources :organisms

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/faq'

end

app/models/mutation.rb
class Mutation < ActiveRecord::Base
	has_many :stats, :dependent => :destroy
	has_many :genes, :through => :stats
	has_many :mutpubs, :dependent => :destroy
	has_many :publications, :through => :mutpubs

	accepts_nested_attributes_for :mutpubs, :allow_destroy => true
	accepts_nested_attributes_for :publications, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true

	validates :nucleotide, :aminoacid,  presence: true, uniqueness: true
	
	def self.search (search) 
      where("nucleotide like ? OR aminoacid like ?", "%#{search}%", "%#{search}%")
    end

    def allmut
    	"Nucleotide: #{nucleotide} => Aminoacid: #{aminoacid}"
    end
end

app/controllers/mutations_controller.rb
class MutationsController < ApplicationController
  before_action :set_mutation, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:show, :edit, :new, :destroy, :update, :create]
  # GET /mutations
  # GET /mutations.json
  def index
    if params[:search]
      @mutations = Mutation.search(params[:search]).order(:nucleotide, :aminoacid).paginate(:per_page => 3, :page => params[:page])
    else
      @mutations = Mutation.all.order(:nucleotide, :aminoacid).paginate(:per_page => 3, :page => params[:page])
    end
  end

  # GET /mutations/1
  # GET /mutations/1.json
  def show
  end

  # GET /mutations/new
  def new
    @mutation = Mutation.new
  end

  # GET /mutations/1/edit
  def edit
  end

  # POST /mutations
  # POST /mutations.json
  def create
    @mutation = Mutation.new(mutation_params)

    respond_to do |format|
      if @mutation.save
        format.html { redirect_to @mutation, notice: 'Mutation was successfully created.' }
        format.json { render :show, status: :created, location: @mutation }
      else
        format.html { render :new }
        format.json { render json: @mutation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutations/1
  # PATCH/PUT /mutations/1.json
  def update
    respond_to do |format|
      if @mutation.update(mutation_params)
        format.html { redirect_to @mutation, notice: 'Mutation was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutation }
      else
        format.html { render :edit }
        format.json { render json: @mutation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutations/1
  # DELETE /mutations/1.json
  def destroy
    @mutation.destroy
    respond_to do |format|
      format.html { redirect_to mutations_url, notice: 'Mutation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutation
      @mutation = Mutation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutation_params
      params.require(:mutation).permit(:nucleotide, :aminoacid, :hgvs)
    end
end

app/helpers/mutations_helper.rb
module MutationsHelper
end

app/views/mutations/_form.html.erb
<div class="panel panel-info">
<div class="panel-heading"><strong>Mutation</strong></div>
<div class="panel-body">
<%= form_for @mutation, :html => { :class => "form-horizontal mutation" } do |f| %>

    <% if @mutation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@mutation.errors.count, "error") %> prohibited this mutation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @mutation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Nucleotide, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nucleotide, :class => 'form-control' %>
    </div>
    <%= error_span(@mutation[:nucleotide]) %>
  </div>
  <div class="control-group">
    <%= f.label :Aminoacid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :aminoacid, :class => 'form-control' %>
    </div>
    <%= error_span(@mutation[:aminoacid]) %>
  </div>
  <div class="control-group">
    <%= f.label :HGVS, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hgvs, :class => 'form-control' %>
    </div>
    <%= error_span(@mutation[:hgvs]) %>
  </div>

  <hr>
  <%= f.submit "Submit", :class => 'btn active btn-sm btn-primary'%>
  <%= link_to " Cancel",
            mutations_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-remove' %>

<% end %>
</div>
</div>

app/views/mutations/edit.html.erb
<%- model_class = Mutation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mutations/index.html.erb
<%- model_class = Mutation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag mutations_path, :method => 'get' do %>
  <div class="input-group">
     <span class="input-group-addon glyphicon glyphicon-search"></span>
    <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Search the Mutation here'%>
    <span class="input-group-addon" id="sizing-addon1"><%= submit_tag "Search", :name=> nil %></span>
  </div>
<%end%>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="info"><%= model_class.human_attribute_name(:ID) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Nucleotide) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Aminoacid) %></th>
      <th class="info"><%= model_class.human_attribute_name(:HGVS) %></th>
      <th class="info"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%if @mutations.any? == true%>
    <% @mutations.each do |mutation| %>
      <tr>
        <td><%= link_to mutation.id, mutation_path(mutation) %></td>
        <td><%= mutation.nucleotide %></td>
        <td><%= mutation.aminoacid %></td>
        <td><%= mutation.hgvs %></td>
        <td>
          <%= link_to " show", mutation_path(mutation), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
          <%= link_to " edit", edit_mutation_path(mutation), :class => 'btn active btn-default btn-xs glyphicon glyphicon-edit' %>
          <%= link_to " Delete", mutation_path(mutation),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure you want delete this Mutation?'},
                      :class => 'btn active btn-xs btn-danger glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
    <%else%>
      <tr>
          <td colspan="5"><%= "Don't exist mutations"%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<div class="pager btn-sm" align="center">
  <%= will_paginate @mutations %>
  </div>
<hr>
<%= link_to " New Gene",
            new_mutation_path,
            :class => 'btn active btn-sm btn-primary glyphicon glyphicon-plus-sign' %>

app/views/mutations/new.html.erb
<%- model_class = Mutation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mutations/show.html.erb
<%- model_class = Mutation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Nucleotide) %>:</strong></dt>
  <dd><%= @mutation.nucleotide %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Aminoacid) %>:</strong></dt>
  <dd><%= @mutation.aminoacid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:HGVS) %>:</strong></dt>
  <dd><%= @mutation.hgvs %></dd>

  <hr>
    <div class="panel panel-info">
      <div class="panel-heading" style="font-size: 18px" align="center"><b> Associated Genes: </b></div>
         
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:Information) %></th>
                <th><%= model_class.human_attribute_name(:Number_of_Studies) %></th>
                <th><%= model_class.human_attribute_name(:Name) %></th>
                <th><%= model_class.human_attribute_name(:Reference) %></th>
                <th><%= model_class.human_attribute_name(:Sequence) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% if @mutation.genes.any? == true %>
              <% @mutation.stats.each do |gene| %>
                <tr>
                  <td><%= gene.info %></td>
                  <td><%= gene.n_studies %></td>
                  <td><%= gene.gene.name %></td>
                  <td><%= gene.gene.reference %></td>
                  <td><%= gene.gene.sequence %></td>
                  <td>
                    <%= link_to "Go to Gene", gene_path(gene.gene.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %>
                    <%= link_to " Show association", stat_path(gene.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
                  </td>
                </tr>
              <% end %>
              <%else%>
                <tr>
                    <td colspan="6"><%= "This mutation don't have associated genes" %></td>
                </tr>
              <%end%>
            </tbody>
            </table>
    </div>
    <%= form_tag new_stat_path, :method => 'get' do %>
          <div class="input-group">
            <strong><%=" Do you need a new gene for this Mutation, with ID   "%>
            <%= text_field_tag :newm, @mutation.id, :readonly => true, :class => 'textbox' %></strong>
            <%= submit_tag "New Gene", :name=> nil, :class => 'btn active btn-sm btn-primary' %>
          </div>
        <%end%>
    <hr>
    <div class="panel panel-info">
      <div class="panel-heading" style="font-size: 18px" align="center"><b> Related Publications: </b></div>
      
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:Title) %></th>
                <th><%= model_class.human_attribute_name(:Author) %></th>
                <th><%= model_class.human_attribute_name(:Date) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <%if @mutation.publications.any? == true %>
              <% @mutation.mutpubs.each do |publication| %>
                <tr>
                  <td><%= publication.publication.title %></td>
                  <td><%= publication.publication.author %></td>
                  <td><%= publication.publication.date %></td>
                  <td>
                    <%= link_to "Go to Publication", publication_path(publication.publication.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %>
                    <%= link_to " Show association", mutpub_path(publication.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
                  </td>
                </tr>
              <% end %>
              <%else%>
                <tr>
                      <td colspan="4"><%= "This mutation don't have related publications" %></td>
                </tr>
              <%end%>
            </tbody>
            </table>
    </div>
    <%= form_tag new_mutpub_path, :method => 'get' do %>
          <div class="input-group">
            <strong><%=" Do you need a new publication for this Mutation, with ID   "%>
            <%= text_field_tag :newm, @mutation.id, :readonly => true, :class => 'textbox' %></strong>
            <%= submit_tag "New Publication", :name=> nil, :class => 'btn active btn-sm btn-primary' %>
          </div>
    <%end%>
</dl>
<hr>
<%= link_to " Back", mutations_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-share-alt'  %>
<%= link_to " Edit", edit_mutation_path(@mutation), :class => 'btn active btn-sm btn-default glyphicon glyphicon-edit' %>
<%= link_to " Delete", mutation_path(@mutation),
              :method => 'delete',
              :data => { :confirm => 'Are you sure you want delete this mutation?' },
              :class => 'btn active btn-sm btn-danger glyphicon glyphicon-remove' %>