config/routes.rb
Rails.application.routes.draw do

  resources :createorganism
  resources :createorigin
  resources :createdrug
  resources :createmutation
  resources :dashboards

  resources :mutpubs

  devise_for :users
  resources :haves

  resources :publications

  resources :stats

  resources :mutations

  resources :genes

  resources :drugs

  resources :resists

  resources :isolateds

  resources :origins

  resources :organisms

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/faq'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	has_many :mutpubs, :dependent => :destroy
	has_many :mutations, :through => :mutpubs

	validates :author, :title, :date, :journal,  presence: true
	validates :author, length: { maximum: 30}
	validates :title, length: { maximum: 100}, uniqueness: true
	validates :journal, length: { maximum: 100}

	def self.search (search) 
      where("title like ? OR author like ? OR date like ? OR journal like ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:show, :edit, :new, :destroy, :update, :create]
  # GET /publications
  # GET /publications.json
  def index
     if params[:search]
      @publications = Publication.search(params[:search]).order(:title, :author, :date, :journal).paginate(:per_page => 3, :page => params[:page])
    else
      @publications = Publication.all.order(:title, :author, :date, :journal).paginate(:per_page => 3, :page => params[:page])
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:author, :title, :date, :journal)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<div class="panel panel-info">
<div class="panel-heading"><strong>Publication</strong></div>
<div class="panel-body">
<%= form_for @publication, :html => { :class => "form-horizontal publication" } do |f| %>

    <% if @publication.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @publication.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'form-control' %>
    </div>
    <%= error_span(@publication[:author]) %>
  </div>
  <div class="control-group">
    <%= f.label :Title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@publication[:title]) %>
  </div>
  <div class="control-group">
    
    <%= f.label :Date, :class => 'control-label' %>
    <div class="controls">
      <p id="date">
      <%= f.date_select :date, :class => 'form-control' %>
      </p>
    </div>
    <%= error_span(@publication[:date]) %>
  
  </div>
  <div class="control-group">
    <%= f.label :Journal, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :journal, :class => 'form-control' %>
    </div>
    <%= error_span(@publication[:journal]) %>
  </div>

  <hr>
  <%= f.submit "Submit", :class => 'btn active btn-sm btn-primary'%>
  <%= link_to " Cancel",
            publications_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-remove' %>

<% end %>
</div>
</div>

app/views/publications/edit.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/publications/index.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag publications_path, :method => 'get' do %>
  <div class="input-group">
     <span class="input-group-addon glyphicon glyphicon-search"></span>
    <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Search the Publication here'%>
    <span class="input-group-addon" id="sizing-addon1"><%= submit_tag "Search", :name=> nil %></span>
  </div>
<%end%>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="info"><%= model_class.human_attribute_name(:ID) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Author) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Title) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Date) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Journal) %></th>
      <th class="info"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @publications.any? == true%>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= link_to publication.id, publication_path(publication) %></td>
        <td><%= publication.author %></td>
        <td><%= publication.title %></td>
        <td><%= publication.date %></td>
        <td><%= publication.journal %></td>
        <td>
          <%= link_to " show", publication_path(publication), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
          <%= link_to " edit", edit_publication_path(publication), :class => 'btn active btn-default btn-xs glyphicon glyphicon-edit' %>
          <%= link_to " Delete", publication_path(publication),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure you want delete this Publication?'},
                      :class => 'btn active btn-xs btn-danger glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
    <% else %>
      <tr>
            <td colspan="6"><%= "Don't exist publications" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pager btn-sm" align="center">
  <%= will_paginate @publications %>
</div>
<hr>
<%= link_to " New Publication",
            new_publication_path,
            :class => 'btn active btn-sm btn-primary glyphicon glyphicon-plus-sign' %>

app/views/publications/new.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/publications/show.html.erb
<%- model_class = Publication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Author) %>:</strong></dt>
  <dd><%= @publication.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Title) %>:</strong></dt>
  <dd><%= @publication.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Date) %>:</strong></dt>
  <dd><%= @publication.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Journal) %>:</strong></dt>
  <dd><%= @publication.journal %></dd>
  <hr>
    <div class="panel panel-info">
      <div class="panel-heading" style="font-size: 18px" align="center"><b>Mutations Associated: </b></div>
      
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:Nucleotide) %></th>
                <th><%= model_class.human_attribute_name(:Aminoacid) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% if @publication.mutations.any? == true %>
              <% @publication.mutpubs.each do |mutation| %>
                <tr>
                  <td><%= mutation.mutation.nucleotide %></td>
                  <td><%= mutation.mutation.aminoacid %></td>
                  <td>
                    <%= link_to "Go to Mutation", mutation_path(mutation.mutation.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %>
                    <%= link_to " Show association", mutpub_path(mutation.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
                  </td>
                </tr>
              <% end %>
              <% else %>
                <tr>
                    <td colspan="3"><%= "This publication don't have mutations associated" %></td>
                </tr>
              <% end %>
            </tbody>
            </table>
    </div>
    <%= form_tag new_mutpub_path, :method => 'get' do %>
          <div class="input-group">
            <strong><%=" Do you need a new mutation for this Publication, with ID   "%>
            <%= text_field_tag :newp, @publication.id, :readonly => true, :class => 'textbox' %></strong>
            <%= submit_tag "New Mutation", :name=> nil, :class => 'btn active btn-sm btn-primary' %>
          </div>
    <%end%>
</dl>
<hr>
<%= link_to " Back", publications_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-share-alt'  %>
<%= link_to " Edit", edit_publication_path(@publication), :class => 'btn active btn-sm btn-default glyphicon glyphicon-edit' %>
<%= link_to " Delete", publication_path(@publication),
              :method => 'delete',
              :data => { :confirm => 'Are you sure you want delete this publication?' },
              :class => 'btn active btn-sm btn-danger glyphicon glyphicon-remove' %>