config/routes.rb
Rails.application.routes.draw do

  resources :createorganism
  resources :createorigin
  resources :createdrug
  resources :createmutation
  resources :dashboards

  resources :mutpubs

  devise_for :users
  resources :haves

  resources :publications

  resources :stats

  resources :mutations

  resources :genes

  resources :drugs

  resources :resists

  resources :isolateds

  resources :origins

  resources :organisms

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/faq'

end

app/models/gene.rb
class Gene < ActiveRecord::Base
  belongs_to :isolated
  has_many :stats, :dependent => :destroy
  has_many :mutations, :through => :stats

  accepts_nested_attributes_for :stats, :reject_if => lambda { |a| a[:info].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :mutations, :reject_if => lambda { |a| a[:nucleotide].blank? }, :allow_destroy => true

  validates :name, :reference, :sequence,  presence: true
  validates :reference, uniqueness: true, numericality: { only_integer: true}
  validates :name, length: { maximum: 30}
  
  def self.search (search) 
      where("name like ? OR reference like ? OR sequence like ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/controllers/genes_controller.rb
class GenesController < ApplicationController
  before_action :set_gene, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:show, :edit, :new, :destroy, :update, :create]
  before_action :set_isolated, only: [:new, :edit, :update, :create]

  # GET /genes
  # GET /genes.json
  def index
    if params[:search]
      @genes = Gene.search(params[:search]).order(:name, :reference).paginate(:per_page => 3, :page => params[:page])
    else
      @genes = Gene.all.order(:name, :reference).paginate(:per_page => 3, :page => params[:page])
    end
  end

  # GET /genes/1
  # GET /genes/1.json
  def show
  end

  # GET /genes/new
  def new
    @gene = Gene.new
    @isol = params[:newg] #isolated.id
  end

  # GET /genes/1/edit
  def edit
  end

  # POST /genes
  # POST /genes.json
  def create
    @gene = Gene.new(gene_params)

    respond_to do |format|
      if @gene.save
        format.html { redirect_to @gene, notice: 'Gene was successfully created.' }
        format.json { render :show, status: :created, location: @gene }
      else
        format.html { render :new }
        format.json { render json: @gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genes/1
  # PATCH/PUT /genes/1.json
  def update
    respond_to do |format|
      if @gene.update(gene_params)
        format.html { redirect_to @gene, notice: 'Gene was successfully updated.' }
        format.json { render :show, status: :ok, location: @gene }
      else
        format.html { render :edit }
        format.json { render json: @gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genes/1
  # DELETE /genes/1.json
  def destroy
    @gene.destroy
    respond_to do |format|
      format.html { redirect_to genes_url, notice: 'Gene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gene
      @gene = Gene.find(params[:id])
    end

  

    # Never trust parameters from the scary internet, only allow the white list through.
    def gene_params
      params.require(:gene).permit(:name, :sequence, :reference, :uniprot, :symbol, :isolated_id)
    end

    def set_isolated
        @isolateds = Isolated.all
    end
end

app/helpers/genes_helper.rb
module GenesHelper


end

app/views/genes/_form.html.erb
<div class="panel panel-info">
<div class="panel-heading"><strong>Gene</strong></div>
<div class="panel-body">
<%= form_for @gene, :html => { :class => "form-horizontal gene" } do |f| %>

    <% if @gene.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@gene.errors.count, "error") %> prohibited this gene from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @gene.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Name_of_Gene, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@gene[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :Sequence, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sequence, :class => 'form-control' %>
    </div>
    <%= error_span(@gene[:sequence]) %>
  </div>
  <div class="control-group">
    <%= f.label :Reference, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reference, :class => 'form-control' %>
    </div>
    <%= error_span(@gene[:reference]) %>
  </div>
  <div class="control-group">
    <%= f.label :UniProt, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uniprot, :class => 'form-control' %>
    </div>
    <%= error_span(@gene[:uniprot]) %>
  </div>
  <div class="control-group">
    <%= f.label :Symbol, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :symbol, :class => 'form-control' %>
    </div>
    <%= error_span(@gene[:symbol]) %>
  </div>
  <div class="control-group">
    <% if @isol == nil%>
         <%= f.label :Choose_the_Isolated_Associate, :class => 'control-label' %>
         <%= f.collection_select :isolated_id, @isolateds, :id, :name, prompt: true, :class => 'form-control' %>
    <%else%>
         <%= f.label :Isolated, :class => 'control-label' %>
         <%= f.collection_select :isolated_id, @isolateds, :id, :name, :selected => "#{@isol}" %>
    <%end%>
  </div>

  <hr>
  <%= f.submit "Submit", :class => 'btn active btn-sm btn-primary'%>
  <%= link_to " Cancel",
            genes_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-remove' %>
<% end %>
</div>
</div>

app/views/genes/edit.html.erb
<%- model_class = Gene -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/genes/index.html.erb
<%- model_class = Gene -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag genes_path, :method => 'get' do %>
  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-search"></span>
    <%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Search the Gene here'%>
    <span class="input-group-addon" id="sizing-addon1"><%= submit_tag "Search", :name=> nil %></span>
  </div>
<%end%>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="info"><%= model_class.human_attribute_name(:ID) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Name) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Sequence) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Reference) %></th>
      <th class="info"><%= model_class.human_attribute_name(:UniProt) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Symbol) %></th>
      <th class="info"><%= model_class.human_attribute_name(:Isolated_Associate) %></th>
      <th class="info"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if @genes.any? == true%>
    <% @genes.each do |gene| %>
      <tr>
        <td><%= link_to gene.id, gene_path(gene) %></td>
        <td><%= gene.name %></td>
        <td><%= gene.sequence %></td>
        <td><%= gene.reference %></td>
        <td><%= gene.uniprot %></td>
        <td><%= gene.symbol %></td>
        <td><%= gene.isolated.name %></td>
        <td>
          <%= link_to " show", gene_path(gene), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
          <%= link_to " edit", edit_gene_path(gene), :class => 'btn active btn-default btn-xs glyphicon glyphicon-edit' %>
          <%= link_to " Delete", gene_path(gene),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure you want delete the Gene?'},
                      :class => 'btn active btn-xs btn-danger glyphicon glyphicon-remove' %>
        </td>
      </tr>
    <% end %>
    <%else%>
      <tr>
        <td colspan="8"><%= "Don't exist genes" %></td>
      </tr>
    <%end%>
  </tbody>
</table>
 <div class="pager btn-sm" align="center">
  <%= will_paginate @genes %>
  </div>
<hr>
<%= link_to " New Gene",
            new_gene_path,
            :class => 'btn active btn-sm btn-primary glyphicon glyphicon-plus-sign' %>

app/views/genes/new.html.erb
<%- model_class = Gene -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/genes/show.html.erb
<%- model_class = Gene -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Name) %>:</strong></dt>
  <dd><%= @gene.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Sequence) %>:</strong></dt>
  <dd><%= @gene.sequence %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Reference) %>:</strong></dt>
  <dd><%= @gene.reference %></dd>
  <dt><strong><%= model_class.human_attribute_name(:UniProt) %>:</strong></dt>
  <dd><%= @gene.uniprot %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Symbol) %>:</strong></dt>
  <dd><%= @gene.symbol %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Isolated_Associate) %>:</strong></dt>
  <dd><%= @gene.isolated.name %></dd>
  <dd><%= link_to "Go to Isolated", isolated_path(@gene.isolated.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %></dd>

<hr>
    <div class="panel panel-info">
      <div class="panel-heading" style="font-size: 18px" align="center"><b> Your Mutations: </b></div>
      
          <table class="table table-striped">
            <thead>
              <tr>
                <th><%= model_class.human_attribute_name(:Information) %></th>
                <th><%= model_class.human_attribute_name(:Number_of_Studies) %></th>
                <th><%= model_class.human_attribute_name(:Nucleotide) %></th>
                <th><%= model_class.human_attribute_name(:Aminoacid) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
              <% if @gene.mutations.any? == true %>
              <% @gene.stats.each do |mutation| %>
                <tr>
                  <td><%= mutation.info %></td>
                  <td><%= mutation.n_studies %></td>
                  <td><%= mutation.mutation.nucleotide %></td>
                  <td><%= mutation.mutation.aminoacid %></td>
                  <td>
                    <%= link_to "Go to Mutation", mutation_path(mutation.mutation.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-open' %>
                    <%= link_to " Show association", stat_path(mutation.id), :class => 'btn active btn-default btn-xs glyphicon glyphicon-new-window' %>
                  </td>
                </tr>
              <% end %>
              <% else %>
                  <tr>
                    <td colspan="5"><%= "This Gene don't have mutations"%></td>
                 </tr>
              <%end%>
            </tbody>
            </table>
    </div>
</dl>
        <%= form_tag new_stat_path, :method => 'get' do %>
          <div class="input-group">
            <strong><%=" Do you need a new mutation for this Gene, with ID   "%>
            <%= text_field_tag :new, @gene.id, :readonly => true, :class => 'textbox' %></strong>
            <%= submit_tag "New Mutation", :name=> nil, :class => 'btn active btn-sm btn-primary' %>
          </div>
        <%end%>
<hr>
<%= link_to " Back", genes_path, :class => 'btn active btn-sm btn-default glyphicon glyphicon-share-alt'  %>
<%= link_to " Edit", edit_gene_path(@gene), :class => 'btn active btn-sm btn-default glyphicon glyphicon-edit' %>
<%= link_to " Delete", gene_path(@gene),
              :method => 'delete',
              :data => { :confirm => 'Are you sure you want delete the Gene?' },
              :class => 'btn active btn-danger btn-sm glyphicon glyphicon-remove' %>